on:
  push:
     branches:
       - main
jobs:
  bookdown:
    name: Render-Book
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v1
        env:
          TINYTEX_INSTALLER: TinyTeX
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v2
        with:
          name: _book
          path: _book/
